config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  root 'home#index'

  devise_scope :user do
     get 'users/sign_out' => "devise/sessions#destroy"
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/personal.rb
class Personal < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)
    # @friend = current_user.friends.bulid(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
  def about
    @about_me  = "My name is KHSA"
    @answer = 2 + 3
  end
end

app/controllers/personals_controller.rb
class PersonalsController < ApplicationController
  before_action :set_personal, only: %i[ show edit update destroy ]

  # GET /personals or /personals.json
  def index
    @personals = Personal.all
  end

  # GET /personals/1 or /personals/1.json
  def show
  end

  # GET /personals/new
  def new
    @personal = Personal.new
  end

  # GET /personals/1/edit
  def edit
  end

  # POST /personals or /personals.json
  def create
    @personal = Personal.new(personal_params)

    respond_to do |format|
      if @personal.save
        format.html { redirect_to personal_url(@personal), notice: "Personal was successfully created." }
        format.json { render :show, status: :created, location: @personal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personals/1 or /personals/1.json
  def update
    respond_to do |format|
      if @personal.update(personal_params)
        format.html { redirect_to personal_url(@personal), notice: "Personal was successfully updated." }
        format.json { render :show, status: :ok, location: @personal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personals/1 or /personals/1.json
  def destroy
    @personal.destroy

    respond_to do |format|
      format.html { redirect_to personals_url, notice: "Personal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal
      @personal = Personal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def personal_params
      params.require(:personal).permit(:first_name, :last_name, :email, :phone, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/personals_helper.rb
module PersonalsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="field form-group">
<%= form.text_field :first_name, class:"form-control", placeholder: "First Name" %>
</div>
 <div class="field form-group">
  
    <%= form.text_field :last_name ,class:"form-control",placeholder:"LastName" %>
  </div>

  <div class="field form-group">
   
    <%= form.text_field :email,class:"form-control",placeholder:"Email"  %>
  </div>

  <div class="field form-group">

    <%= form.text_field :phone,class:"form-control" ,placeholder:"Phone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter,class:"form-control" ,placeholder:"twitter" %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control" ,value: current_user.id, type: :hidden %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>
</div>

app/views/friends/delete.html.erb
<h1>Delete friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend,
class: "btn btn-dark" %> 
  <%= link_to "Back", friends_path,
  class: "btn btn-dark" %>
</div>

app/views/friends/edit.html.erb
<h1>Edit Friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <h1>Friend List</h1>

  <%= link_to "New friend", new_friend_path, class: "btn btn-sm btn-secondary my-3" %>

  <div id="friends">
    <table class="table">
        <thead>
          <th scope="score">Name</th>
          <th scope="score">Email</th>
          <th scope="score">Phone</th>
          <th scope="score">Twitter</th>
        </thead>
        <tbody>
        <% @friends.each do |friend| %>
          <% if friend.user == current_user %>
            <tr>
              <td><%= link_to friend.first_name + " " + friend.last_name, friend %></td>
              <td><%= friend.email %></td>
              <td><%= friend.phone %></td>
              <td><%= friend.twitter %></td>
            </tr>
          <% end %>
        <% end %>
    </tbody>
  </table>
  </div>
<% else %>
  <h1>Home Page</h1>
<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>

<%= render "form", friend: @friend %>

<br>
<div>
  <%= link_to "Back", friends_path,class:'btn btn-secondary' %>
</div>

app/views/friends/show.html.erb
<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %><%= @friend.last_name %></h1>
  <p class="lead"> 
  <%= @friend.email %>  |
  <%= @friend.phone %>  |
  <%= @friend.twitter %>
  </p>
  <br>
  <%= link_to "Edit", edit_friend_path(@friend),class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path,class:"btn btn-secondary" %>
</div>


<%# <%= render @friend %> 


  

  

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
        <%= link_to "Friends",friends_path, class:"nav-link" %>
          
        </li>
        
            <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class: "nav-link" %>
         </li>


         <% if user_signed_in? %>

          <li class="nav-item">
        <%= link_to "AddFriends",new_friend_path, class:"nav-link" %>
          
        </li>
        
          <li class="nav-item">
        <%= link_to "SignOut",destroy_user_session_path,method: :delete, class:"nav-link" %>
          
        </li>
        <li class="nav-item">
        <%= link_to "Edit profile",edit_user_registration_path, class:"nav-link" %>

        <% else %>


         <li class="nav-item">
        <%= link_to "SignUp",new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "SignIn",new_user_session_path, class:"nav-link" %>
        </li>
        <% end %>

        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us..... </h1>
<p>
<%= @about_me %>
</p>

<p>
2 + 3 = <%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World</h1>
This is my first  Webpage.....

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_alerts_html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
 <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">    <title>Friends List App</title>
</head>
<body>
<%= render 'home/header' %>
<div class="container">
<% if notice %>
<%= render 'layouts/alert' %>
<% end %>
<br>
 
 
 <%= yield %>
 </div>
 <!-- Optional JavaScript; choose one of the two! -->
 <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <!-- Option 2: jQuery, Popper.js, and Bootstrap JS    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>    
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>    
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>    -->
  </body>
  </html>























 

app/views/personals/_form.html.erb
<%= form_with(model: personal) do |form| %>
  <% if personal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(personal.errors.count, "error") %> prohibited this personal from being saved:</h2>

      <ul>
        <% personal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :twitter, style: "display: block" %>
    <%= form.text_field :twitter %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/personals/_personal.html.erb
<div id="<%= dom_id personal %>">
  <p>
    <strong>First name:</strong>
    <%= personal.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= personal.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= personal.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= personal.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= personal.twitter %>
  </p>

</div>

app/views/personals/edit.html.erb
<h1>Editing personal</h1>

<%= render "form", personal: @personal %>

<br>

<div>
  <%= link_to "Show this personal", @personal %> |
  <%= link_to "Back to personals", personals_path %>
</div>

app/views/personals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Personals</h1>

<div id="personals">
  <% @personals.each do |personal| %>
    <%= render personal %>
    <p>
      <%= link_to "Show this personal", personal %>
    </p>
  <% end %>
</div>

<%= link_to "New personal", new_personal_path %>

app/views/personals/new.html.erb
<h1>New personal</h1>

<%= render "form", personal: @personal %>

<br>

<div>
  <%= link_to "Back to personals", personals_path %>
</div>

app/views/personals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @personal %>

<div>
  <%= link_to "Edit this personal", edit_personal_path(@personal) %> |
  <%= link_to "Back to personals", personals_path %>

  <%= button_to "Destroy this personal", @personal, method: :delete %>
</div>